# Generated by Django 5.1.4 on 2025-01-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TaskManager", "0002_baseentity_rename_author_id_task_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseentity",
            name="id",
            field=models.CharField(
                editable=False,
                max_length=40,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
