# Generated by Django 5.1.4 on 2025-04-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TaskManager", "0003_alter_baseentity_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("done", "Done"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
    ]
